M48
; DRILL file {KiCad 7.0.2} date di 01 aug 2023 17:34:10 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-01T17:34:10+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1004
%
G90
G05
T1
X2.9744Y-1.6185
X2.9744Y-1.8461
T2
X2.9187Y-3.613
T3
X2.6719Y-3.513
T0
M30
